# @package _global_

# Usage: ./train.py +overfit=overfit

data:
  train:
    max_samples: 6400
  val:
    max_samples: 6400
    epoch_interval: 1
  test:
    max_samples: 3200
    epoch_interval: 1

logging:
  tags: ['overfit']
