defaults:
  - model/vit_global_obj
  - data/clevr10
  - losses/l_global/ctr
  - losses/l_objects/ctr_img
  - optimizer/adam
  - lr_scheduler/linear1_cosine4_x10
  - logging/wandb
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

training:
  batch_size: 64
  num_epochs: null # defaults to warmup + decay

other:
  debug: no
  seed: null # defaults to random
  device: 'cuda:0'
